config/routes.rb
Modera::Engine.routes.draw do
  resources :banea_dominios, except: [:show]
end

app/models/modera/banea_dominio.rb
module Modera
  class BaneaDominio < ActiveRecord::Base
    NO_BANEABLES = %w(gmail yahoo hotmail outlook live.com telefonica movistar rankia verema)

    default_scope { order(:dominio) }

    validates :dominio, presence: true, uniqueness: true
    validate :dominio_es_baneable

    before_validation { dominio.try(:downcase!) }

    protected

    def dominio_es_baneable
      if dominio_con_formato_incorrecto?
        errors.add(:dominio, 'El dominio introducido tiene un formato incorrecto')
      elsif dominio_listado_como_no_baneable?
        errors.add(:dominio, 'Este dominio no puede ser baneado')
      end
    end

    def dominio_con_formato_incorrecto?
      formato_dominio = '[a-z\d\-]+\.'
      formato_sufijo = '[a-z]+'

      dominio !~ /\A(#{ formato_dominio })+#{ formato_sufijo }\z/i
    end

    def dominio_listado_como_no_baneable?
      formato_subdominio = '[a-z\d\-]+\.'
      formato_sufijo = '\.[a-z]+'

      NO_BANEABLES.any? do |no_baneable|
        dominio =~ /\A(#{ formato_subdominio })*#{ no_baneable }(#{ formato_sufijo }){,2}\z/i
      end
    end
  end
end

app/controllers/modera/application_controller.rb
module Modera
  class ApplicationController < ActionController::Base
  end
end

app/controllers/modera/banea_dominios_controller.rb
module Modera
  class BaneaDominiosController < InheritedResources::Base
    before_filter :gestor_usr_required

    def create
      @banea_dominio = BaneaDominio.new(dominio: params[:banea_dominio][:dominio],
                                        updated_usuario: @yo.nick)
      create! { banea_dominios_path }
    end

    def update
      @banea_dominio = BaneaDominio.find(params[:id])
      @banea_dominio.updated_usuario = @yo.nick
      update! { banea_dominios_path }
    end

    protected

    def permitted_params
      params.permit(banea_dominio: [:dominio])
    end
  end
end

app/helpers/modera/application_helper.rb
module Modera
  module ApplicationHelper
  end
end

app/views/layouts/modera/application.html.haml
!!!
%html
  %head
    %title Modera
    = stylesheet_link_tag    "modera/application", media: "all"
    = javascript_include_tag "modera/application"
    = csrf_meta_tags
  %body
    = yield

app/views/modera/banea_dominios/_form.html.haml
= form_for @banea_dominio do |f|
  = render 'web/muestra_errores_form', variable: @banea_dominio
  = f.label(:dominio, 'Dominio:')
  = f.text_field :dominio, required: true, autofocus: true, placeholder: 'Ej: trashmail.com'
  = f.submit 'Guardar'

app/views/modera/banea_dominios/edit.html.haml
.new_edit
  %h1 Edición de dominio de correo baneado
.new_edit_marco
  = render 'form'

= link_to 'Volver', banea_dominios_path

app/views/modera/banea_dominios/index.html.haml
.banea-dominios
  %h1 Lista de dominios de correo baneados

  = link_to 'Añadir dominio baneado', new_banea_dominio_path
  %br/
  %br/
  %table.table-striped
    %tr.cabecera-tabla
      %th Dominio
      %th Control
      %th

    - @banea_dominios.each do |dominio_baneado|
      %tr
        %td= dominio_baneado.dominio
        %td= link_to 'Editar', edit_banea_dominio_path(dominio_baneado)
        %td= link_to 'Borrar', dominio_baneado, method: :delete, data: { confirm: '¿Estás seguro?' }

app/views/modera/banea_dominios/new.html.haml
.new_edit
  %h1 Nuevo dominio de correo baneado
.new_edit_marco
  = render 'form'

= link_to 'Volver', banea_dominios_path